# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        # run: pip install --upgrade pip
        run: pip install -r requirements.txt
      # - name: Run pytest
        # run: pytest
      - name: Run pylint
        run: pylint certcheck
      # - name: Install Docker
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get upgrade -y
      #     sudo apt-get -y install docker.io

  checkov-docker:
    runs-on: ubuntu-latest
    container:
      image: g12m0/testcheckov:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run IaC check
        run: |
          checkov -v
          cat /etc/os-release
      # - name: Run IaC check
      #   using: 'docker'
      #   image: 'docker://ghcr.io/bridgecrewio/checkov:2.3.238'
      # run: |
      #     docker run --rm \
      #       -v $(pwd):/workdir \
      #       g12m0/testcheckov:latest \
      #       -d /workdir
