# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pylint
        run: |
          echo "Running pylint: " $PWD
          pylint --exit-zero --reports=n certcheck
          
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: |
          echo "Running pytest: " $PWD
          pytest

  checkov-docker:
    runs-on: ubuntu-latest
    container:
      image: g12m0/testov:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run IaC check
        run: |
          echo "Running IaC check: " $PWD
          checkov -d . --shoft-fail
