# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     python-version: ["3.8", "3.9", "3.10"]

    steps:
      # - uses: actions/checkout@v3
      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Analysing the code with pylint
        run: |
          echo "Running pylint: " $PWD
          # pylint $(git ls-files '*.py')
          pylint --exit-zero --reports=n certcheck
          
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Analysing the code with pytest
        run: |
          echo "Running pytest: " $PWD
          pytest

  checkov-docker:
    runs-on: ubuntu-latest
    container:
      image: g12m0/testov:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Analysing the code with checkov for IaC
        run: |
          echo "Running IaC check: " $PWD
          checkov -d . --soft-fail
  